<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="SergioIzq.Application.Kernel" Version="0.2.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kash.Domain\Kash.Domain.csproj" />
    <ProjectReference Include="..\Kash.Shared.Domain\Kash.Shared.Domain.csproj" />
  </ItemGroup>

</Project>
